
# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
    properties:
      hibernate:
        cache:
          redis:
            expiryInSeconds:
              default: 120
          redisson:
            config: redisson.yaml
            com.example.demojpa.User:
              timestamps:
                eviction.max_entries: 60
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: spring
    producer:
      bootstrap-servers: 127.0.0.1:9092
  application:
    name: ok




  security.oauth2.resource.load-balanced = true
  security.oauth2.resource.token-info-uri = http://localhost:8080/oauth/check_token
  security.oauth2.resource.user-info-uri= http://localhost:8080/user/me

  spring.security.user.name=admin
  spring.security.user.password=admin

  #security.oauth2.client.client-id=app
  #security.oauth2.client.client-secret=app

  logging.level.org.springframework.security = debug

  security.oauth2.resource.jwt.key-value = -----BEGIN PUBLIC KEY-----\
  MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTDS4uMpGXhxDkkueDgMy/Jr9a\
  Gyy3lgklhi271ZKAi+PmLEKTEyAzK07MxmuXC9bAajOMYXAzf8KDuU0gx/pf1tTz\
  EJx5V2Nkqe1TZE4rHrBiyN2a5LAf0GD6owwkk0nLUA0iehiNgDDT70CtqPov9tME\
  tj0hGydV1JTltEtqMQIDAQAB\
  -----END PUBLIC KEY-----